var events = [
    {
        name: "Final Round",
        locationCity:"Atlanta",
        locationState:"GA",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 18,
        startYear: 2016,
        endMonth: 10,
        endDate: 20,
        endYear: 2016,
        eventType: "Premier",
        LocationLatitude: 33.748995,
        LocationLongitude: -84.387982,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/02/final-round.jpg",
        imageAlt: "Final Round"
    },
    {
        name: "NorCal Regionals",
        locationCity:"Sacramento",
        locationState:"CA",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 25,
        startYear: 2016,
        endMonth: 10,
        endDate: 27,
        endYear: 2016,
        eventType: "Premier",
        LocationLatitude: 38.581572,
        LocationLongitude: -121.4944,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2016/02/norcal-regionals-2016.jpg", 
        imageAlt: "NorCal Regionals"
    },
    {
        name: "West Coast Warzone",
        locationCity:"Los Angeles",
        locationState:"CA",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 15,
        startYear: 2016,
        endMonth: 10,
        endDate: 17,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 34.052234,
        LocationLongitude: -118.243685,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2016/02/west-coast-warzone-5.jpg",
        imageAlt: "West Coast Warzone" 
    },
    {
        name: "Texas Showdown",
        locationCity:"Houston",
        locationState:"TX",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 22,
        startYear: 2016,
        endMonth: 10,
        endDate: 24,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 29.760427,
        LocationLongitude: -95.369803,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2016/02/ts-logo-400x200.jpg",
        imageAlt: "Texas Showdown"
    },
    {
        name: "Dreamhack Austin",
        locationCity:"Austin",
        locationState:"TX",
        locationCountry: "USA",
        startMonth: 11,
        startDate: "06",
        startYear: 2016,
        endMonth: 11,
        endDate: "08",
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 30.267153,
        LocationLongitude: -97.743061,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/02/dreamhack.jpg",
        imageAlt: "Dreamhack Austin"
    },
    {
        name: "Combo Breaker",
        locationCity:"Chicago",
        locationState:"IL",
        locationCountry: "USA",
        startMonth: 11,
        startDate: 27,
        startYear: 2016,
        endMonth: 11,
        endDate: 29,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 41.878114,
        LocationLongitude: -87.629798,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2015/02/combo-breaker.jpg",
        imageAlt: "ComboBreaker"
    },
    
    {
        name: "Community Effort Orlando",
        locationCity:"Orlando",
        locationState:"FL",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 24,
        startYear: 2016,
        endMonth: 10,
        endDate: 26,
        endYear: 2016,
        eventType: "Premier",
        LocationLatitude: 28.5383355,
        LocationLongitude: -81.37923649999999,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/02/community-effort-orlando.jpg",
        imageAlt: "CEO"
    },
    {
        name: "Evolution Championship Series",
        locationCity:"Las Vegas",
        locationState:"NV",
        locationCountry: "USA",
        startMonth: 9,
        startDate: 15,
        startYear: 2016,
        endMonth: 9,
        endDate: 17,
        endYear: 2016,
        eventType: "Championship",
        LocationLatitude: 36.1699412, 
        LocationLongitude: 115.13982959999998, 
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/02/evo.jpg",
        imageAlt: "Evolution Championship Series"
    },
    {
        name: "Defend the North",
        locationCity:"White Plains",
        locationState:"NY",
        locationCountry: "USA",
        startMonth: 7,
        startDate: 29,
        startYear: 2016,
        endMonth: 7,
        endDate: 31,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 41.03398620000001, 
        LocationLongitude: 73.76290970000002, 
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2015/02/defend-the-north.jpg",
        imageAlt: "Defend the North",
    },
    {
        name: "Summer Jam",
        locationCity:"Philadelphia",
        locationState:"PA",
        locationCountry: "USA",
        startMonth: 8,
        startDate: 19,
        startYear: 2016,
        endMonth: 8,
        endDate: 21,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 39.9525839,
        LocationLongitude: -75.16522150000003,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2016/02/summer-jam.jpg",
        imageAlt: "Summer Jam"
    },
    {
        name: "Absolute Battle",
        locationCity:"Dallas",
        locationState:"TX",
        locationCountry: "USA",
        startMonth: 8,
        startDate: 26,
        startYear: 2016,
        endMonth: 8,
        endDate: 28,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 32.7766642,
        LocationLongitude: -96.79698789999998,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2016/02/absolute-battle-7.jpg",
        imageAlt: "Absolute Battle"
    },
    {
        name: "East Coast Throwdown",
        locationCity:"Morristown",
        locationState:"NJ",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 13,
        startYear: 2016,
        endMonth: 10,
        endDate: 14,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 40.7967667,
        LocationLongitude: -74.4815438,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/04/east-coast-throwdown.jpg",
        imageAlt: "East Coast Throwdown"
    },
    {
        name: "The Fall Classic",
        locationCity:"Raleigh",
        locationState:"NC",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 07,
        startYear: 2016,
        endMonth: 10,
        endDate: 09,
        endYear: 2016,
        eventType: "Ranking",
        LocationLatitude: 35.7795897,
        LocationLongitude: -78.63817870000003,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/02/the-fall-classic.jpg", 
        imageAlt: "The Fall Classic"
    },
    {
        name: "SoCal Regionals",
        locationCity:"Los Angeles",
        locationState:"CA",
        locationCountry: "USA",
        startMonth: 10,
        startDate: 14,
        startYear: 2016,
        endMonth: 10,
        endDate: 16,
        endYear: 2016,
        eventType: "Premier",
        LocationLatitude: 34.0522342,
        LocationLongitude: -118.2436849,
        imageSrc: "http://capcomprotour.com/wp-content/uploads/2014/03/socal-regionals-2014.jpg",
        imageAlt: "Socal Regionals"
    },

]